name: Deploy homepage to deploy branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the homepage
        run: npm run build

      - name: Deploy to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: dist
          clean: true
